### ISSUE TITLE
각 서비스(카카오, 구글, 트위터)에 개발자 계정 만들어오기

### ISSUE THREAD

**Issue by failed-commune** [hex-head/myKeyword#3]
트위터 로그인 doc : https://developer.twitter.com/en/docs/authentication/guides/log-in-with-twitter
카카오 로그인 doc : https://developers.kakao.com/docs/latest/ko/kakaologin/common
구글 로그인 doc : https://developers.google.com/identity/sign-in/web/sign-in

**Comment by failed-commune** [comment]
test

**Comment by failed-commune** [comment]
카카오 개발자 앱 만들었는데, 카카오 계정 알려주시면 팀초대 해놓겠습니다.
트위터는 승인같은 것이조금 필요해서 시간이 걸릴것 같은데, 완료되면 공유드릴게요.

**Comment by OHHAKO** [comment]
khk0503@icloud.com 카카오톡 로그인할때 쓰는 메일입니다
